wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1692536406.156062
    t:
      1:
      - 1
      - 55
      - 76
      - 105
      2:
      - 1
      - 55
      - 76
      - 105
      3:
      - 2
      - 16
      - 23
      4: 3.10.10
      5: 0.15.8
      8:
      - 1
      - 2
      - 4
      - 5
